### PR TITLE
Set up Budget Feature

### PR DESCRIPTION
**Pull request by jonahansmulcrone**

### CODE REVIEW

**Review by colestewart12 — COMMENTED** [review]
The code looks great, nice job!

I would take a look at the merge conflicts and then we can approve and merge this PR.

**Comment by jonahansmulcrone** [comment]
Is this good to merge?

**Comment by jonahansmulcrone** [comment]
how do I get an approving review for this pr?

**Review by jonahansmulcrone — COMMENTED** [review]
Looks good!

**Review by colestewart12 — APPROVED** [review]

**Pull request merged**
